// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
module.exports = {
  addonType: "plugin",
  id: "piranha305_queue",
  name: "Queue",
  version: "1.0.0.0",
  category:
    // "3d",
    "data-and-storage",
    // "form-controls",
    // "input",
    // "media",
    // "monetisation",
    // "platform-specific",
    // "web",
    // "other"
    // "general",
  author: "piranha305",
  website: "https://www.construct.net",
  documentation: "https://www.construct.net",
  description: "A Construct 3 plugin to store and retrieve data in a queue data structure.",
  // addonUrl: "https://www.construct.net/en/make-games/addons/####/XXXX", // displayed in auto-generated docs
  // githubUrl: "https://github.com/skymen/XXXX", // displays latest release version in auto-generated docs
  // icon: "icon.svg", // defaults to "icon.svg" if omitted
  type: "object",   // world, object, dom
  domSideScripts: [
    // "domSide.js", // no need to include "c3runtime/" prefix
  ],
  fileDependencies: [
    /*
    {
      filename: "filename.js", // no need to include "c3runtime/" prefix
      type:
        "copy-to-output"
        "inline-script"
        "external-dom-script"
        "external-runtime-script"
        "external-css"

      // for copy-to-output only
      // fileType: "image/png"
    }
    */
  ],
  info: {
    // world only
    defaultImageUrl: null,
    Set: {
      // world only
      IsResizable: false,
      IsRotatable: false,
      Is3D: false,
      HasImage: false,
      IsTiled: false,
      SupportsZElevation: false,
      SupportsColor: false,
      SupportsEffects: false,
      MustPreDraw: false,

      // object only
      IsSingleGlobal: true,

      // world and object
      CanBeBundled: true,
      IsDeprecated: false,
      GooglePlayServicesEnabled: false,
    },
    AddCommonACEs: {
      // world only
      Position: false,
      SceneGraph: false,
      Size: false,
      Angle: false,
      Appearance: false,
      ZOrder: false,
    },
  },
  properties: [
    /*
    {
      type:
        "integer"
        "float"
        "percent"
        "text"
        "longtext"
        "check"
        "font"
        "combo"
        "color"
        "object"
        "group"
        "link"
        "info"

      id: "property_id",
      options: {
        initialValue: 0,
        interpolatable: false,

        // minValue: 0, // omit to disable
        // maxValue: 100, // omit to disable

        // for type combo only
        // items: [
        //   {itemId1: "item name1" },
        //   {itemId2: "item name2" },
        // ],

        // dragSpeedMultiplier: 1, // omit to disable

        // for type object only
        // allowedPluginIds: ["Sprite", "<world>"],

        // for type link only
        // linkCallback: `function(instOrObj) {}`,
        // linkText: "Link Text",
        // callbackType:
        //   "for-each-instance"
        //   "once-for-type"

        // for type info only
        // infoCallback: `function(inst) {}`,
      },
      name: "Property Name",
      desc: "Property Description",
    }
    */
  ],
  aceCategories: {
    // follows the format id: langName
    // in the ACEs refer to categories using the id, not the name
    general: "General",
  },
  Acts: {
    Enqueue: {
      category: "general",
      forward: "Enqueue",
      autoScriptInterface: true,
      highlight: false,
      params: [
        {
          id: "value",
          name: "Value",
          desc: "The value to enqueue.",
          type: "any",
        },
      ],
      listName: "Enqueue",
      displayText: "Insert [i]{0}[/i] in queue.",
      description: "Adds a value to the end of the queue.",
    },
    EnqueueWithPiority: {
      category: "general",
      forward: "EnqueueWithPiority",
      autoScriptInterface: true,
      highlight: false,
      params: [
        {
          id: "value",
          name: "Value",
          desc: "The value to enqueue.",
          type: "any",
        },
        {
          id: "priority",
          name: "Priority",
          desc: "The priority of the value.",
          type: "number",
        }
      ],
      listName: "Enqueue with priority",
      displayText: "Insert [i]{0}[/i] in queue with priority [i]{1}[/i].",
      description: "Adds a value to the end of the queue with a priority.",
    },
    Dequeue: {
      category: "general",
      forward: "Dequeue",
      autoScriptInterface: true,
      highlight: false,
      params: [],
      listName: "Dequeue",
      displayText: "Remove first item from queue.",
      description: "Dequeues a value. (can access item from LastDequeuedValue expression)",
    },
    Clear: {
      category: "general",
      forward: "Clear",
      autoScriptInterface: true,
      highlight: false,
      params: [],
      listName: "Clear",
      displayText: "Clear queue.",
      description: "Clears the queue.",
    },
    Shuffle: {
      category: "general",
      forward: "Shuffle",
      autoScriptInterface: true,
      highlight: false,
      params: [],
      listName: "Shuffle",
      displayText: "Shuffle queue.",
      description: "Randomly shuffles queue.",
    },
    LoadFromJSON: {
      category: "general",
      forward: "LoadFromJSON",
      autoScriptInterface: true,
      highlight: false,
      params: [
        {
          id: "json",
          name: "JSON",
          desc: "The JSON string to load.",
          type: "string",
        }
      ],
      listName: "Load from JSON",
      displayText: "Load queue from JSON [i]{0}[/i].",
      description: "Loads the queue from a JSON string.",
    },
    /*
    SampleAction: {
      // The category of the action as it appears in the add action dialog
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this action
      // Cases where you might not want this are:
      // 1- If the action params are incompatible with the script interface
      // 2- If you don't want it to appear in the script interface
      // 3- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the action in the add action dialog
      highlight: false,

      // Set to true to hide the action in the interface. False by default if not specified.
      deprecated: false,

      // Marks the action as async. Defaults to false if not specified.
      isAsync: false,

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
            - "boolean"

            // The following types can take a default value but CANNOT be automatically generated in the script interface
            - "combo"

            // The following types CANNOT take a default value AND CANNOT be automatically generated in the script interface
            - "cmp"
            - "object"
            - "objectname"
            - "layer"
            - "layout"
            - "keyb"
            - "instancevar"
            - "instancevarbool"
            - "eventvar"
            - "eventvarbool"
            - "animation"
            - "objinstancevar"

          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "the default value of the parameter",

          // Only for type "combo"
          items: [
            {"itemId1": "itemName1"},
            {"itemId2": "itemName2"},
            {"itemId3": "itemName3"},
          ],

          // Only for type "object"
          allowedPluginIds: ["Sprite", "TiledBg"],
        },
      ],

      // The name of the action as it appears in the add action dialog
      listName: "Sample Action",

      // The text that appears in the event sheet. Note, every single param must be used in the display text.
      // You can also use [b] and [i] tags.
      displayText: "Sample action [i]{0}[/i]",

      // The description of the action as it appears in the add action dialog
      description: "This is a sample action",
    },
    */
  },
  Cnds: {
    IsEmpty: {
      category: "general",
      forward: "IsEmpty",
      autoScriptInterface: true,
      highlight: false,
      params: [],
      description: "Returns true if the queue is empty.",
      listName: "Is empty",
      displayText: "Is queue empty?",
    },
    HasItems:{
      category: "general",
      forward: "HasItems",
      autoScriptInterface: true,
      highlight: false,
      params: [],
      description: "Returns true if the queue has items.",
      listName: "Has items",
      displayText: "Does queue have items?",
    },
    OnLastItemDequeued: {
      category: "general",
      forward: "OnLastItemDequeued",
      autoScriptInterface: true,
      highlight: false,
      isTrigger: true,
      params: [],
      description: "Triggered when the last item is dequeued.",
      listName: "On last item dequeued",
      displayText: "On last item dequeued",
    },
    OnItemQueued: {
      category: "general",
      forward: "OnItemQueued",
      autoScriptInterface: true,
      highlight: false,
      isTrigger: true,
      params: [],
      description: "Triggered when an item is queued. (can access item from LastQueued expression)",
      listName: "On item queued",
      displayText: "On item queued",
    },
    OnItemDequeued: {
      category: "general",
      forward: "OnItemDequeued",
      autoScriptInterface: true,
      highlight: false,
      isTrigger: true,
      params: [],
      description: "Triggered when an item is dequeued. (can access item from LastDequeuedValue expression)",
      listName: "On item dequeued",
      displayText: "On item dequeued",
    }
    /*
    SampleCondition: {
      // The category of the action as it appears in the add condition dialog
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this condition
      // Cases where you might not want this are:
      // 1- If the condition params are incompatible with the script interface
      // 2- If you don't want it to appear in the script interface
      // 3- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the condition in the add condition dialog
      highlight: false,

      // Set to true to hide the condition in the interface. False by default if not specified.
      deprecated: false,

      // special conditions properties. These can all be omitted, and they will default to the following values:
      isTrigger: false,
      isFakeTrigger: false,
      isStatic: false,
      isLooping: false,
      isInvertible: true,
      isCompatibleWithTriggers: true,

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
            - "boolean"

            // The following types can take a default value but CANNOT be automatically generated in the script interface
            - "combo"

            // The following types CANNOT take a default value AND CANNOT be automatically generated in the script interface
            - "cmp"
            - "object"
            - "objectname"
            - "layer"
            - "layout"
            - "keyb"
            - "instancevar"
            - "instancevarbool"
            - "eventvar"
            - "eventvarbool"
            - "animation"
            - "objinstancevar"

          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "the default value of the parameter",

          // Only for type "combo"
          items: [
            {"itemId1": "itemName1"},
            {"itemId2": "itemName2"},
            {"itemId3": "itemName3"},
          ],

          // Only for type "object"
          allowedPluginIds: ["Sprite", "TiledBg"],
        },
      ],

      // The name of the condition as it appears in the add condition dialog
      listName: "Sample Condition",

      // The text that appears in the event sheet. Note, every single param must be used in the display text.
      // You can also use [b] and [i] tags.
      displayText: "Sample condition [i]{0}[/i]",

      // The description of the condition as it appears in the add condition dialog
      description: "This is a sample condition",
    },
    */
  },
  Exps: {
    LastDequeuedValue: {
      category: "general",
      forward: "LastDequeuedValue",
      autoScriptInterface: true,
      highlight: false,
      params: [],
      returnType: "any",
      description: "Returns the last dequeued value.",
    },
    Size: {
      category: "general",
      forward: "Size",
      autoScriptInterface: true,
      highlight: false,
      params: [],
      returnType: "number",
      description: "Returns the size of the queue.",
    },
    Peek:{
      category: "general",
      forward: "Peek",
      autoScriptInterface: true,
      highlight: false,
      params: [],
      returnType: "any",
      description: "Gets the value at the front of the queue without removing it",
    },
    Pop: {
      category: "general",
      forward: "Pop",
      autoScriptInterface: true,
      highlight: false,
      params: [],
      returnType: "any",
      description: "Dequeues a value and returns it.",
    },
    PeekLast: {
      category: "general",
      forward: "PeekLast",
      autoScriptInterface: true,
      highlight: false,
      params: [],
      returnType: "any",
      description: "Returns the last item in the queue. (does not remove it from queue)",
    },
    LastQueued: {
      category: "general",
      forward: "LastQueued",
      autoScriptInterface: true,
      highlight: false,
      params: [],
      returnType: "any",
      description: "Returns the last queued value.",
    },
    AsJSON: {
      category: "general",
      forward: "AsJSON",
      autoScriptInterface: true,
      highlight: false,
      params: [],
      returnType: "string",
      description: "Returns the queue as a JSON string.",
    }
    /*
    SampleExpression: {
      // The category of the action as it appears in the expression picker
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this expression
      // Cases where you might not want this are:
      // 1- If you don't want it to appear in the script interface
      // 2- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the expression in the expression picker
      highlight: false,

      // Set to true to hide the expression in the interface. False by default if not specified.
      deprecated: false,

      // The type of the expression.
      returnType:
        - "string"
        - "number"
        - "any" // must be either string or number

      // Set to true if the expression is variadic. False by default if not specified.
      isVariadicParameters: false

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
        },
      ],

      // The description of the expression as it appears in the expression picker
      description: "This is a sample expression",
    },
    */
  },
};
